css = "text/css"
gif = "image/gif"
htm = "text/html"
html = "text/html"
jpeg = "image/jpeg"
jpg = "image/jpg"
js = "text/javascript"
json = "application/json"
png = "image/png"
text = "text/plain; charset=utf-8"
txt = "text/plain"